### ISSUE TITLE
Database Schema and Seed

### ISSUE THREAD

**Issue by mdwiltfong** [hazeltonbw/ecommerce-backend#5]
Hey Brandon! 

The level of detail in your api is great! I love the documentation, comments and especially how you compartmentalize your code. 

The first thing I encountered is the lack of a database schema. Without one, it can be difficult to reproduce your API locally on another machine. 

This can be solved a couple of ways. You can provide a simply formatted doc that explains the schema of your database, which will enable others to manually run the necessary SQL commands to create the database locally. Or, you can write the sql files for contributors to execute locally. 

Here's an [example](https://github.com/mdwiltfong/reactive-weather-app/tree/master/database) where you can see `weather.sql`. When users execute `weather.sql` in their local database, it will then guide them through seeding and creating the needed database to interact with the app. 

I'd love to help out with this so I can further explore the app!

**Comment by hazeltonbw** [comment]
> Hey Brandon!
> 
> The level of detail in your api is great! I love the documentation, comments and especially how you compartmentalize your code.
>
Thank you for your kindness! 

> The first thing I encountered is the lack of a database schema. Without one, it can be difficult to reproduce your API locally on another machine.
> 
> This can be solved a couple of ways. You can provide a simply formatted doc that explains the schema of your database, which will enable others to manually run the necessary SQL commands to create the database locally. Or, you can write the sql files for contributors to execute locally.
> 
> Here's an [example](https://github.com/mdwiltfong/reactive-weather-app/tree/master/database) where you can see `weather.sql`. When users execute `weather.sql` in their local database, it will then guide them through seeding and creating the needed database to interact with the app.
> 
I have created a new branch for this issue, 
[5-database-schema-and-seed](https://github.com/hazeltonbw/ecommerce-backend/tree/5-database-schema-and-seed)
In this new branch I have created a script in the package.json file called `create-db`, you can run it with `npm run create-db` so that the tables will be created in your database. Be sure to set up your environment file with the appropriate values first. I have included an **example.env** file that is similar to mine so you can get it set up relatively easy. Let me know if there's anything else needed, can't wait to hear back! Thanks

**Comment by hazeltonbw** [comment]
Database schema and seed has been updated to match the new database schema. Users can view the schema by referencing the [ERD](https://raw.githubusercontent.com/hazeltonbw/ecommerce-backend/5-database-schema-and-seed/resources/ERD-new.png). There is also an SQL file that users can choose to run or just use the script provided in package.json called `create-db`.
